### ISSUE TITLE
Question: Pair Sequence Classification

### ISSUE THREAD

**Issue by FahadEbrahim** [EveripediaNetwork/fastc#10]
Hi,

Does the library support pair sequence classification (input1, input2, label)? 

Thanks.

**Comment by brunneis** [comment]
Hi @FahadEbrahim,

There is no direct support for pair sequence classification but I'm pretty sure you can make it work by defining a template for that specific task with an instruct model such as `intfloat/multilingual-e5-large-instruct`: https://github.com/EveripediaNetwork/fastc?tab=readme-ov-file#templates-and-instruct-models

**Comment by FahadEbrahim** [comment]
Thank you @brunneis for your prompt feedback, clarification and suggestion.
