### ISSUE TITLE
Support for multiclass?

### ISSUE THREAD

**Issue by micuentadecasa** [EveripediaNetwork/fastc#5]
Hi, I wanted to know if this library support multiclass, multilabel classification?

**Comment by brunneis** [comment]
Hi @micuentadecasa,

Absolutely! You can load a dataset that includes all the classes you need. For example, [tinyroberta-6l-768d-language-identifier-en-es-ko-zh-fastc](https://huggingface.co/braindao/tinyroberta-6l-768d-language-identifier-en-es-ko-zh-fastc) provides labels for four different languages.

**Comment by micuentadecasa** [comment]
Hi @brunneis , I'm not sure to understand your approach, I explain you my dataset, I have a text and multiple possible labels
text1, category1, category3
text2, category4
text3, category1, category4

and I need to pass a text, and get the categories that fits, so the questions/needs that I have are:
- what is the format of the dataset that I have to pass to fastc?
- how can I use spanish language in the texts and categories? (maybe the model that you mentioned and some parameter)
- some sample code for multilabel classification

Regards.

**Comment by brunneis** [comment]
Sorry, @micuentadecasa, I misunderstood your earlier question. There isn't built-in multiclass support, but you can work around this by using multiple classifiers. For instance, you could employ multiple binary classifiers, each dedicated to a specific label. Alternatively, if you can group related labels into clusters, you might use binary classifiers for each cluster and then additional classifiers for each label within the clusters.

The purpose of this library is to create lightweight classifiers that can run in parallel with minimal overhead while using the same model for embeddings. Thus, the previous approach might be practical for your needs.

**Comment by micuentadecasa** [comment]
I see now @brunneis , I will take a look to that approach, thanks.
